matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: precise

sudo: false

before_install:
  - ./tests/cfg/pki/create_tsa_certs

addons:
  apt:
    packages:
      - cmake
      - time
      - valgrind
      - libc6-dev
      - gcc
      - g++
      - libssl-dev
    sources:
      - kubuntu-backports

language: c

compiler: clang

script: cmake . -DBUNDLE_CIVETWEB=ON && make && ./tests/external_test.sh
